"""statuses init

Revision ID: 3bf81f373e39
Revises: 85f5708679da
Create Date: 2024-08-19 00:29:27.848505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3bf81f373e39'
down_revision: Union[str, None] = '85f5708679da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_status = sa.Enum('active', 'inactive', 'deleted', name='_status')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _status.create(op.get_bind())
    op.add_column('club__car', sa.Column('status', _status, nullable=True, server_default='active'))
    op.add_column('club__club', sa.Column('status', _status, nullable=True, server_default='active'))
    op.add_column('club__raceway', sa.Column('status', _status, nullable=True, server_default='active'))
    op.add_column('session__result', sa.Column('status', _status, nullable=True, server_default='active'))
    op.add_column('session__session', sa.Column('status', _status, nullable=True, server_default='active'))
    op.add_column('user__racer', sa.Column('status', _status, nullable=True, server_default='active'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user__racer', 'status')
    op.drop_column('session__session', 'status')
    op.drop_column('session__result', 'status')
    op.drop_column('club__raceway', 'status')
    op.drop_column('club__club', 'status')
    op.drop_column('club__car', 'status')
    _status.drop(op.get_bind())
    # ### end Alembic commands ###
