"""init raceway model

Revision ID: 85f5708679da
Revises: 
Create Date: 2024-08-06 22:07:52.552380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '85f5708679da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club__club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user__racer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('avatar', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('second_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('club__raceway',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['club_id'], ['club__club.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('club__car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('power', sa.Float(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.Column('raceway_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['raceway_id'], ['club__raceway.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session__session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('description', sa.JSON(), nullable=True),
    sa.Column('club_id', sa.Integer(), nullable=False),
    sa.Column('raceway_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['raceway_id'], ['club__raceway.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session__result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('laps', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('racer_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['club__car.id'], ),
    sa.ForeignKeyConstraint(['racer_id'], ['user__racer.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session__session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session__result')
    op.drop_table('session__session')
    op.drop_table('club__car')
    op.drop_table('club__raceway')
    op.drop_table('user__racer')
    op.drop_table('club__club')
    # ### end Alembic commands ###
